### ISSUE TITLE
GIMME output doesn't make sense

### ISSUE THREAD

**Issue by bpuniya** [BioSystemsUM/troppo#12]
Hi Skapur,

I'm using  _GIMME_ method from troppo to construct a tissue-specific model.
I mapped my gene expression data and created an object _expVectore_.

Now, I am running the following script. 

idx_objective = rx_names.index('biomass_reaction')
properties = GIMMEProperties(exp_vector=expVector,
                            obj_frac=0.9,
                            objectives= [{idx_objective:1}],
                            preprocess=True,
                            flux_threshold=0.9
                            )
algorithm = GIMME(S, lb.astype(float), ub.astype(float), properties)
model_GIMME = algorithm.run()

model_GIMME_final = model_cobra.copy()
r_ids = [r.id for r in model_GIMME_final.reactions]
to_remove_ids = [r_ids[r] for r in np.where(model_GIMME==0)[0]]
model_GIMME_final.remove_reactions(to_remove_ids,True)

In the model_GIMME_final, all the reactions assigned 0 in _exp_vector_ were removed, which means GIMMEProperties (obj_frac =0.9) has no impact. Ideally, GIMME should retain some reactions based on the obj_frac argument. 
model_GIMME_final.optimize() results in 0. 

Would you please help me resolve why GIMME is not considering objective function when removing the model?

Thank you!

**Comment by skapur** [comment]
Hi @bpuniya and sorry for the delayed response,

Thanks for pointing this issue! Indeed there was a problem with the GIMME algorithm where the objective reaction bounds were not being set properly, leading to rubbish solutions with null objective values and no added reactions.

Since GIMME is still a part of cobamp we applied the fix in this [commit](https://github.com/BioSystemsUM/cobamp/commit/3d68f66ab3733077aa9fd12839008d92a296863d). It should work now and your solutions should start including other reactions 

I can't release a fix on PyPI today but if you want to use this right now, you can replace line 740 on cobamp/core/models.py with these two:
`lbs_id = objective_lbs[objective_ids]`
`for id, lb in zip(objective_ids, lbs_id):`

I will keep this issue open until we release a new version on PyPI.

Once again, thank you for taking the time to report this to us!

**Comment by bpuniya** [comment]
Hi @skapur 

Thank you very much for your response and for resolving this issue.  
It is working fine now. 

Thanks again!
